name: CI - Pipeline de Extracao

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  testes-unitarios:
    name: Validar Testes com Pytest
    runs-on: ubuntu-latest
    
    steps:
      - name: Fazer Checkout do Código
        uses: actions/checkout@v4
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10" # Utilize a versão de Python do seu projeto local
          
      - name: Instalar e Configurar o Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.2
          virtualenvs-create: true
          virtualenvs-in-project: true
          
      - name: Carregar Cache de Dependências
        uses: actions/cache@v4
        id: cached-poetry-dependencies
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
          
      - name: Instalar Dependências
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
        
      - name: Executar Pytest
        run: poetry run pytest tests/